apiVersion: v1
kind: Service
metadata:
  labels:
    app: fibonaci
  name: fibonaci
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30425
  selector:
    app: fibonaci
  type: NodePort
